import = ["/Users/forrest/dotfiles/alacritty/theme/solarized_light.toml"]

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.normal]
style = "Regular"

[window]
decorations = "buttonless"

[window.dimensions]
columns = 86
lines = 44

[window.padding]
x = 5
y = 5

[window.position]
x = 2560
y = 0
